name: cefops
description: Portal Do Aluno Escola Almeida Santos.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.14.2 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  flutter_localizations: {sdk: flutter}
  cupertino_icons: ^1.0.2
  websafe_platform: ^1.2.0-nullsafety.0
  get: ^4.1.4
  http: ^0.13.3
  google_fonts: ^2.1.0
  provider: ^6.0.1
  intl: ^0.17.0
  syncfusion_flutter_pdf: ^19.2.47-beta
  path_provider: any
  open_file: any
  universal_html: ^2.0.8
  syncfusion_flutter_calendar: ^19.2.60
  dropdown_plus: ^0.0.9
  crypto: ^3.0.1
  convert: ^3.0.0
  fluttertoast: ^8.0.7
  flutter_screenutil: ^5.0.0+2
  dio_cookie_manager: ^2.0.0
  flutter_svg: ^0.22.0
  basic_utils: ^3.9.4
dev_dependencies:
  flutter_test: {sdk: flutter}
flutter:
  uses-material-design: true
  assets: [assets/images/asssinatura.png, assets/images/cefops1_orig.png, assets/images/enfermagem.jpg,
    assets/images/fundo.png, assets/images/icon_add.png, assets/images/icon_blogger.png,
    assets/images/icon_home.png, assets/images/icon_logout.png, assets/images/icon_search.png,
    assets/images/icon_settings.png, assets/images/logo.png, assets/images/logo2.png,
    assets/images/logo_branco_Laranja.png, assets/images/Logo_Digital.png, assets/images/logo_Lara.png,
    assets/images/logoBranca.png, assets/images/logoV2.png, assets/images/logoV4.png,
    assets/images/novohead.png, assets/images/rodape.png]
