/// Generated by AssetsRefGenerator on 2021/11/04
class Res {
  static const String asssinatura = "assets/images/asssinatura.png";
  static const String cefops1_orig = "assets/images/cefops1_orig.png";
  static const String enfermagem = "assets/images/enfermagem.jpg";
  static const String fundo = "assets/images/fundo.png";
  static const String icon_add = "assets/images/icon_add.png";
  static const String icon_blogger = "assets/images/icon_blogger.png";
  static const String icon_home = "assets/images/icon_home.png";
  static const String icon_logout = "assets/images/icon_logout.png";
  static const String icon_search = "assets/images/icon_search.png";
  static const String icon_settings = "assets/images/icon_settings.png";
  static const String logo = "assets/images/logo.png";
  static const String logo2 = "assets/images/logo2.png";
  static const String logo_branco_Laranja = "assets/images/logo_branco_Laranja.png";
  static const String Logo_Digital = "assets/images/Logo_Digital.png";
  static const String logo_Lara = "assets/images/logo_Lara.png";
  static const String logoBranca = "assets/images/logoBranca.png";
  static const String logoV4 = "assets/images/logoV4.png";
  static const String rodape = "assets/images/rodape.png";
}
